### ISSUE TITLE
Fails with error "Body is too long" for apps with many stacks/stages

### ISSUE THREAD

**Issue by mrgrain** [corymhall/cdk-diff-action#32]
Hi @corymhall , I tried using this action on a private repo with many stacks to replace a different (but worse) diff tool. You know which repo. It has a lot of stacks and it seems like this causes the action to fail with the following error:

```
Error commenting stages:  RequestError [HttpError]: Validation Failed: {"resource":"IssueComment","code":"unprocessable","field":"data","message":"Body is too long (maximum is 65536 characters)"}
```

Maybe an option to have a comment per stack? Or do some clever magic to shorten the body?

**Comment by corymhall** [comment]
Hey @mrgrain! I'll probably start with trying to split the comments per stack.

**Comment by mrgrain** [comment]
Splitting works great! You are a hero! Came across another size issue #34 for new stacks.
