### ISSUE TITLE
handle authentication issues

### ISSUE THREAD

**Issue by corymhall** [corymhall/cdk-diff-action#35]
I don't think we are currently handling authentication issues very well. We should at a minimum

- Compare the credentials with the stack account and if they don't match, throw an error
- Log a warning if the lookup role is not found

**Comment by mrgrain** [comment]
What is are the requirements for the authenticated role? Are you using the role directly, or does the authenticated role need to be able to assume the lookup role as defined in the app?

**Comment by corymhall** [comment]
If the stack has a lookup role then it will assume that, otherwise it will use the default credentials.
