### ISSUE TITLE
Question: Which version of cdk does this use?

### ISSUE THREAD

**Issue by noel-llevares** [corymhall/cdk-diff-action#63]
Does this action use its own `cdk` or does it use the one in my project's dependencies (e.g. `node_modules`)?

**Comment by corymhall** [comment]
This action doesn't run any cdk commands, so when you run `cdk synth` it will use whatever cdk version you have in your projects dependencies. The action then uses some cdk libraries to inspect the generated `cdk.out` and to generate the diff. The version of those libraries are controlled by the action.

**Comment by noel-llevares** [comment]
Thank you @corymhall .
