### ISSUE TITLE
GitHub Actions can't find the @v1 version of the action

### ISSUE THREAD

**Issue by oehnstro** [corymhall/cdk-diff-action#9]
It seems the example in the readme file is using `@v1` as the version of the action. GitHub can't find this version. Using `@v1.0.0` works, so I guess there either needs to be a new tag/release with just `v1` or the example should be updated to use `v1.0.0`.

The action itself works really well, thank you!

**Comment by corymhall** [comment]
@oehnstro thanks for the feedback! I updated the example in the README
